DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'butler_db') THEN
      CREATE DATABASE butler_db;
   END IF;
END
$$;

\c butler_db

-- TABLE
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID CHAR(36) PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    REGISTERED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--  INDEX
CREATE INDEX IDX_USERS_USERNAME ON USERS(USER_NAME);

-- INITIAL DATA
INSERT INTO USERS (USER_ID, USER_NAME, EMAIL, PASSWORD) VALUES ('0eb82332-a4e3-1051-cda6-5489848296f3', '小比類巻 友翔', 'march09yuuto@gmail.com', '$2a$14$0LlmXvoe/vlD5Zz/koDKje8BxAoVh0fYau3o94rZkVi4Cg.fLiCbW');